
package fr.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentList", targetNamespace = "http://www.test.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentList {


    /**
     * 
     * @param studentA
     */
    @WebMethod(action = "add")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.test.fr", className = "fr.test.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.test.fr", className = "fr.test.AddResponse")
    @Action(input = "add", output = "http://www.test.fr/StudentList/addResponse")
    public void add(
        @WebParam(name = "studentA", targetNamespace = "")
        Student studentA);

    /**
     * 
     * @param studentR
     */
    @WebMethod(action = "removeS")
    @RequestWrapper(localName = "removeS", targetNamespace = "http://www.test.fr", className = "fr.test.RemoveS")
    @ResponseWrapper(localName = "removeSResponse", targetNamespace = "http://www.test.fr", className = "fr.test.RemoveSResponse")
    @Action(input = "removeS", output = "http://www.test.fr/StudentList/removeSResponse")
    public void removeS(
        @WebParam(name = "studentR", targetNamespace = "")
        Student studentR);

    /**
     * 
     * @param indice
     */
    @WebMethod(action = "removeI")
    @RequestWrapper(localName = "removeI", targetNamespace = "http://www.test.fr", className = "fr.test.RemoveI")
    @ResponseWrapper(localName = "removeIResponse", targetNamespace = "http://www.test.fr", className = "fr.test.RemoveIResponse")
    @Action(input = "removeI", output = "http://www.test.fr/StudentList/removeIResponse")
    public void removeI(
        @WebParam(name = "indice", targetNamespace = "")
        int indice);

    /**
     * 
     * @param studentG
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://www.test.fr", className = "fr.test.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://www.test.fr", className = "fr.test.GetInfoResponse")
    @Action(input = "getInfo", output = "http://www.test.fr/StudentList/getInfoResponse")
    public String getInfo(
        @WebParam(name = "studentG", targetNamespace = "")
        Student studentG);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://www.test.fr", className = "fr.test.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://www.test.fr", className = "fr.test.GetListResponse")
    @Action(input = "getList", output = "http://www.test.fr/StudentList/getListResponse")
    public String getList();

}
