
package fr.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentListService", targetNamespace = "http://www.test.fr", wsdlLocation = "file:/home/pima/Documents/FAC/M2/BPM/BPM/src/tp/s1/exercise5/StudentListService.wsdl")
public class StudentListService
    extends Service
{

    private final static URL STUDENTLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTLISTSERVICE_EXCEPTION;
    private final static QName STUDENTLISTSERVICE_QNAME = new QName("http://www.test.fr", "StudentListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/pima/Documents/FAC/M2/BPM/BPM/src/tp/s1/exercise5/StudentListService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTLISTSERVICE_WSDL_LOCATION = url;
        STUDENTLISTSERVICE_EXCEPTION = e;
    }

    public StudentListService() {
        super(__getWsdlLocation(), STUDENTLISTSERVICE_QNAME);
    }

    public StudentListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTLISTSERVICE_QNAME, features);
    }

    public StudentListService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTLISTSERVICE_QNAME);
    }

    public StudentListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTLISTSERVICE_QNAME, features);
    }

    public StudentListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentList
     */
    @WebEndpoint(name = "StudentListPort")
    public StudentList getStudentListPort() {
        return super.getPort(new QName("http://www.test.fr", "StudentListPort"), StudentList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentList
     */
    @WebEndpoint(name = "StudentListPort")
    public StudentList getStudentListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.test.fr", "StudentListPort"), StudentList.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTLISTSERVICE_EXCEPTION!= null) {
            throw STUDENTLISTSERVICE_EXCEPTION;
        }
        return STUDENTLISTSERVICE_WSDL_LOCATION;
    }

}
